---
timezone: America/Sao_Paulo


common_packages_redhat:
  - "@Development tools"
  - bind-utils
  - bc
  - bzip2
  - curl
  - elinks
  - git
  - iperf3
  - iptraf
  - lsof
  - lynx
  - mtr
  - net-tools
  - nmap
  - screen
  - tcpdump
  - telnet
  - unzip
  - vim
  - wget
  - aspell
  - bash-completion
  - tree

common_packages_debian:
  - build-essential
  - net-tools
  - bc
  - sudo
  - screen
  - tcpdump
  - telnet
  - nmap
  - vim
  - tree

